import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/clerk-react";
import { useRouter } from "next/router";
import { Url } from "url";

const inter = Inter({ subsets: ["latin"] });

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router = useRouter();

  const routerPush: RouterFn = (url: Url, options?: TransitionOptions) => {
    return router.push(url, undefined, options);
  };

  const routerReplace: RouterFn = (url: Url, options?: TransitionOptions) => {
    return router.replace(url, undefined, options);
  };

  return (
    <html lang="en">
      <ClerkProvider routerPush={routerPush} routerReplace={routerReplace}>
        <body className={poppins.className}>{children}</body>
      </ClerkProvider>
    </html>
  );
}
